export const SET_LOADING = "SET_LOADING";
export const SET_STEP = "SET_STEP";

// Registration
export const SET_PARTICIPANT_DETAILS = "SET_PARTICIPANT_DETAILS";
export const SET_GUARDIAN_DETAILS = "SET_GUARDIAN_DETAILS";
export const SET_VOLUNTEER_DETAILS = "SET_VOLUNTEER_DETAILS";
export const GET_GRADES = "GET_GRADES";
export const GET_SESSIONS = "GET_SESSIONS";
export const GET_ROLES = "GET_ROLES";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const GRADES_ERROR = "GRADES_ERROR";
export const SESSIONS_ERROR = "SESSIONS_ERROR";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";

// Authentication
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";

// General
export const GENERAL_ERROR = "GENERAL_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Admin
export const GET_DASHBOARD_DATA = "GET_DASHBOARD_DATA";
export const GET_PARTICIPANTS = "GET_PARTICIPANTS";
export const GET_VOLUNTEERS = "GET_VOLUNTEERS";
export const SEARCH_PARTICIPANT = "SEARCH_PARTICIPANT";
export const SEARCH_VOLUNTEER = "SEARCH_VOLUNTEER";
export const ADD_ADMIN = "ADD_ADMIN";
export const DASHB0ARD_DATA_ERROR = "DASHB0ARD_DATA_ERROR";
export const ADD_ADMIN_ERROR = "ADD_ADMIN_ERROR";
export const UPDATE_PARTICIPANT_SUCCESS = "UPDATE_PARTICIPANT_SUCCESS";
export const UPDATE_VOLUNTEER_SUCCESS = "UPDATE_VOLUNTEER_SUCCESS";
export const SET_PARTICIPANT_ID = "SET_PARTICIPANT_ID";
export const GET_PARTICIPANT_ID = "GET_PARTICIPANT_ID";
