export const SET_LOADING = "SET_LOADING";
export const SET_STEP = "SET_STEP";
export const SET_PARTICIPANT_DETAILS = "SET_PARTICIPANT_DETAILS";
export const SET_GUARDIAN_DETAILS = "SET_GUARDIAN_DETAILS";
