export const SET_LOADING = "SET_LOADING";
export const SET_STEP = "SET_STEP";

// Registration
export const SET_PARTICIPANT_DETAILS = "SET_PARTICIPANT_DETAILS";
export const SET_GUARDIAN_DETAILS = "SET_GUARDIAN_DETAILS";
export const SET_VOLUNTEER_DETAILS = "SET_VOLUNTEER_DETAILS";
export const GET_GRADES = "GET_GRADES";
export const REGISTER_PARTICIPANT = "REGISTER_PARTICIPANT";
export const REGISTER_VOLUNTEER = "REGISTER_VOLUNTEER";
export const GRADES_ERROR = "GRADES_ERROR";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";

// Authentication
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";

// General
export const GENERAL_ERROR = "GENERAL_ERROR";

// Admin
export const GET_DASHBOARD_DATA = "GET_DASHBOARD_DATA";
export const GET_PARTICIPANTS = "GET_PARTICIPANTS";
export const GET_VOLUNTEERS = "GET_VOLUNTEERS";
export const SEARCH_PARTICIPANT = "SEARCH_PARTICIPANT";
export const SEARCH_VOLUNTEER = "SEARCH_VOLUNTEER";
export const ADD_ADMIN = "ADD_ADMIN";
export const ADD_ADMIN_ERROR = "ADD_ADMIN_ERROR";
